Add hsp permissions
RedHatInsights/rbac-config pull request #129
Opened 2021-03-02 14:54 UTC by CodeHeeler

Add permissions for historical-system-profiles to Drift in addition to the baselines and comparisons permissions.

2021-03-02 19:03 UTC, coderbydesign approved these changes

2021-03-15 17:02 UTC, coderbydesign requested changes
Please see my comment on your PR regarding structural changes to the config repo.

2021-03-15 18:18 UTC, CodeHeeler commented
Ok, I've rebased to your changes and pushed that up here; the change is now in the /ci/ file specifically.  So we'll hook this up, and then make additional PRs to rbac-config for each environment as we move through them until it's in prod, correct?

2021-03-16 11:26 UTC, coderbydesign commented
@CodeHeeler that's correct! I'll merge these CI changes in and let you know once they're deployed. Then for the other environments, whenever you're ready for them you can just open PRs to those envs.

2021-03-16 11:26 UTC, coderbydesign approved these changes

2021-03-16 11:26 UTC, merged