Add RBAC admin roles for all envs
RedHatInsights/rbac-config pull request #168
Opened 2021-05-25 21:04 UTC by wcmitchell

Needed in preparation for RBAC on RBAC

Signed-off-by: Chris Mitchell <cmitchel@redhat.com>

2021-05-26 17:51 UTC, astrozzc approved these changes
Overall LGTM

2021-05-26 17:51 UTC, astrozzc commented on configs/prod/roles/rbac.json
> +  }
Neat: indentation 😁

2021-06-03 13:41 UTC, coderbydesign requested changes
Looks like a minor typo with the names: `User Access aministrator` - missing the `d`.

2021-06-08 16:03 UTC, coderbydesign approved these changes

2021-06-08 16:10 UTC, merged