Cloud to console for rbac role description
RedHatInsights/rbac-config pull request #226
Opened 2021-11-29 17:55 UTC by john-dupuy

In the UI, I noticed that the role description used `cloud.redhat.com` which may be confusing for users.

2021-12-06 21:00 UTC, astrozzc approved these changes
Thanks for updating this, it has been here for a long time

2022-01-04 11:50 UTC, coderbydesign requested changes
Thanks @john-dupuy! Could you update the PR to only modify the `configs/*` files, and not the `_private/*` files? We have a GitHub action that will update those files by generating new configMaps once the JSON is merged.

2022-01-04 14:34 UTC, john-dupuy commented
> Thanks @john-dupuy! Could you update the PR to only modify the `configs/*` files, and not the `_private/*` files? We have a GitHub action that will update those files by generating new configMaps once the JSON is merged.

Ah thanks for the review - I've just done this!

2022-01-06 18:44 UTC, coderbydesign commented
@john-dupuy sorry, was just going to merge this and realized we need to bump the versions on the roles as well.

2022-01-06 20:02 UTC, coderbydesign approved these changes
Thanks, John!

2022-01-06 20:02 UTC, merged