RHCLOUD-29986 | feature: make Notifications viewer as a default role
RedHatInsights/rbac-config pull request #478
Opened 2023-12-19 10:58 UTC by MikelAlejoBR

We want to encourage users to interact with Notifications more by at least allowing them to see what is configured for their tenants.

## Jira ticket
[[RHCLOUD-29986]](https://issues.redhat.com/browse/RHCLOUD-29986)

2024-01-10 19:46 UTC, astrozzc approved these changes
LGTM!

2024-01-11 11:48 UTC, lpichler commented
NOTE: this probably produces lot of notification events. (as expected)

2024-01-11 13:19 UTC, MikelAlejoBR commented
Thanks for the heads up, @lpichler!

2024-01-12 21:52 UTC, abaiken requested changes
I can do a stage release on this early next week and then we can try a prod release after 🥇

2024-01-12 21:52 UTC, abaiken commented on configs/stage/roles/notifications.json
>        "version": 2,
I think we need to bump the version

2024-01-12 21:52 UTC, abaiken commented on configs/prod/roles/notifications.json
>        "version": 2,
I think we need to bump the version

2024-01-12 22:10 UTC, astrozzc commented on configs/prod/roles/notifications.json
>        "version": 2,
Oh! Right! Good catch!

2024-01-15 12:33 UTC, MikelAlejoBR commented on configs/prod/roles/notifications.json
>        "version": 2,
Changed as well, thanks!

2024-01-15 19:10 UTC, abaiken approved these changes

2024-01-15 19:10 UTC, merged