Update to sources administrator role name (RHCLOUD-31937)
RedHatInsights/rbac-config pull request #492
Opened 2024-04-09 21:20 UTC by rabbott01

Updating the sources administrator role name to "Cloud Administrator" per https://issues.redhat.com/browse/RHCLOUD-31937

2024-04-10 20:20 UTC, petracihalova requested changes
in this case we need to add the `display_name` instead, the `name` should stay same

2024-04-11 01:49 UTC, rabbott01 commented
Thanks @petracihalova - updated and pushed the commits.

2024-04-11 09:02 UTC, petracihalova approved these changes

2024-04-11 10:48 UTC, lpichler approved these changes

2024-04-11 12:44 UTC, merged