Update subscriptions.json
RedHatInsights/rbac-config pull request #497
Opened 2024-06-17 22:03 UTC by rabbott01

Updating "Subscription user" to "Subscription viewer" per RHCLOUD-33136

2024-06-18 04:48 UTC, petracihalova requested changes

2024-06-18 04:48 UTC, petracihalova commented on configs/prod/roles/subscriptions.json
> +      "name": "Subscriptions viewer",
please let the "name" same and add the "display_name" field as we did here https://github.com/RedHatInsights/rbac-config/pull/492

2024-06-18 14:33 UTC, petracihalova commented
> Thanks @petracihalova - I added the "display_name" to Stage/Prod configs.

awesome, thank you for adding "display_name" please can you change back the "name" field?

2024-06-20 12:33 UTC, petracihalova commented on configs/prod/roles/subscriptions.json
> +      "display_name": "Subscription viewer",
```suggestion
      "display_name": "Subscriptions viewer",
```

2024-06-20 13:38 UTC, lpichler commented
@rabbott01 if you can squash commit, it would be awesome!

maybe you can increment version by 1 (no by 2)

2024-06-20 13:51 UTC, merged